version: "3.1"

services:
  dbmigrator-postgres:
    image: postgres:latest
    container_name: dbmigrator-postgres
    ports:
      - "10000:5432"
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

  dbmigrator-mysql:
    image: mysql:latest
    container_name: dbmigrator-mysql
    ports:
      - "10001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test

  dbmigrator-mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: dbmigrator-mssql
    ports:
      - "10002:10002"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Test$123"
      MSSQL_TCP_PORT: 10002
